#! /bin/sh
#AUTOSTART
sxhkd &
nm-applet &
compton --inactive-dim 0.2 &
sh ~/.config/bspwm/monitorsetup
nitrogen --restore &
dunst &
polybar bspwm &
xdo lower -N Polybar &
kitty --class=scratchpad sh ~/.config/bspwm/scratch &
sh ~/Documents/dev/py/Threatron/scripts/pollingservice 300 &
guake &
jetbrains-toolbox &
xinput --set-prop 9 'libinput Accel Speed' 1 &
redshift -O 3100 &
kitty --class=scratchpad2 &
kitty --class=scratchpad3 &
wmname LG3D &
sh ~/.config/bspwm/scratch2 &
sh ~/.config/bspwm/scratch3 &
sh ~/.config/bspwm/fourthws
#bspc desktop 4 focus && cd ~/.config/bspwm/ && sh out.sh &
bspc desktop 1 --activate &

#CONFIG
bspc config border_width 2
bspc config window_gap 15
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config presel_feedback_color \#2e3440
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true





#RULES
bspc rule -a discord:\* desktop=4
bspc rule -a Gpodder:\* hidden=on
bspc rule -a kitty:music desktop=6
bspc rule -a mpv:gl desktop=10
bspc rule -a follow split_dir=south split_ratio=0.8
bspc rule -a scratchpad sticky=on state=floating hidden=on
bspc rule -a scratchpad2:\* state=floating desktop=11
bspc rule -a scratchpad3:\* state=floating desktop=12
bspc rule -a Tc:\* desktop=4
bspc rule -a Guake:\* state=floating center=on
bspc rule -a DeezCord:\* desktop=4
bspc rule -a Deezer:\* desktop=4
bspc rule -a MellowPlayer:\* desktop=4
bspc rule -a qutebrowser:\* desktop=4
bspc rule -a GLava:\* state=floating border=off
