#!/bin/bash
hdmi="$(xrandr | grep 'HDMI-1 connected' && xrandr --output eDP-1 --auto --output HDMI-1 --auto --left-of eDP-1)";
vga="$(xrandr | grep 'VGA-1 connected' && xrandr --output eDP-1 --auto --output VGA-1 --auto --above eDP-1)";
#I either have 2 extra monitors or just one extra monitor, and i never use workspace 0 so we can set it up anyways
if [[ -n $vga ]];then
    bspc monitor eDP-1 -d 1 3 4 5 6 8 9 11 12 13 14
    bspc monitor VGA-1 -d 2 7
    echo "multi-monitor"
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 11 12 13 14
    echo "single monitor"
fi
bspc monitor HDMI-1 -d 10
nitrogen --restore
echo "Done"

