#!/bin/bash
#Takes the currently music played on VLC and puts it into a special little folder
#Or deletes it
musicFolder=~/Downloads/Music/Podcasts/
#Thanks ahrs
file="$(playerctl metadata --player=vlc xesam:url | node -e 'process.stdin.on("readable", () => { const chunk = process.stdin.read(); if ( chunk == null) { return; }; process.stdout.write(decodeURI(chunk).replace("file://", "")); })')"
if [[ $1 == f ]];then
    cp "$file" $musicFolder
fi
if [[ $1 == d ]];then
    rm "$file"
fi
