#!/bin/bash
#Get currently playing song from MellowPlayer history file, which is an sqlite3 thing
#Used for polybar
file=~/.local/share/MellowPlayer/history.db
cp $file ~/go/src/github.com/davidv171/mellowDeezerRPC/
opts=""
title="$(sqlite3 $file 'SELECT songTitle FROM song ORDER BY ID DESC LIMIT 1' $opts)"
artist="$(sqlite3 $file 'SELECT artist FROM song ORDER BY ID DESC LIMIT 1' $opts)"
service="$(sqlite3 $file 'SELECT serviceName from song ORDER BY ID DESC LIMIT 1' $opts)"
echo -e "$service: $artist - $title"
