#!/bin/bash
#When plugging in monitors during run-time the sequence of workspaces gets messed up, compared to when its plugged in during boot up
#What we want: hdmi on ws3 and vga on ws2
xrandr | grep 'HDMI-1 connected' && xrandr --output eDP-1 --auto --output HDMI-1 --auto --left-of eDP-1 && workspace 10 output HDMI-1
xrandr | grep 'VGA-1 connected' && xrandr --output eDP-1 --auto --output VGA-1 --auto --above eDP-1 && workspace 2 output VGA-1
nitrogen --restore

