#! /usr/bin/env bash
#example usage: sh ~/.config/i3/0x0 area
#area = screenshot area and upload to 0x0
#window = screnshot window and upload to 0x0
#screen = screenshot root and upload to 0x0
#4 = upload text currently selected with your mouse to 0x0
#delaya = screenshot area after a delay, needs a second argument, that decides on the delay
case $1 in
    "area"*)
	maim -u ~/Screenshots/Newest/newest.png -s &&
	cd ~/Screenshots/Newest &&
	curl -F'file=@newest.png' https://0x0.st | xclip -i -selection clipboard && xdg-open "$(xclip -o -selection clipboard)" &&
	mv ~/Screenshots/Newest/newest.png ~/Screenshots/"area $(date +%Y-%m-%dT%H:%M:%SZ).png" &&
	notify-send "Area Screenshot in clipboard"
    ;;
    "window"*)
	maim  ~/Screenshots/Newest/window.png -i "$(xdotool getactivewindow)" &&
        cd ~/Screenshots/Newest &&
        curl -F'file=@newest.png' https://0x0.st | xclip -i -selection clipboard &&
	mv ~/Screenshots/Newest/window.png ~/Screenshots/"window $(date +%Y-%m-%dT%H:%M:%SZ).png" &&
        notify-send "Window in clipboard"
    ;;
    "screen"*)
	maim ~/Screenshots/Newest/screen.png &&
	cd ~/Screenshots/Newest &&
	curl -F 'file=@screen.png' https://0x0.st | xclip -i -selection clipboard &&
	mv ~/Screenshots/Newest/screen.png ~/Screenshots/"screen $(date +%Y-%m-%dT%H:%M:%SZ).png" &&
	notify-send "Screen in clipboard"
	;;
    "text"*)
	xclip -o -selection  | curl -F file=@'-' 0x0.st | xclip -i -selection clipboard &&
	notify-send "0x0" "Text in 0x0"
    ;;
    "delaya"*)
	delay=$2
	if [[ -z $2 ]]
	then
	    delay=3
	fi
	maim -s -d "$delay" ~/Screenshots/Newest/delaya.png &&
	cd ~/Screenshots/Newest &&
	curl -F 'file=@delaya.png' 0x0.st | xclip -i -selection clipboard &&
	mv ~/Screenshots/Newest/delaya.png ~/Screenshots/"delayarea $(date +%Y-%m-%dT%H:%M:%SZ).png" &&
	notify-send "Delayed area in clipboard"
    ;;
    "recorda"*)
            giph -s | curl -F 'file=@-' 0x0.st | xclip -i -selection clipboard
    ;;
    "endrecord"*)
        killall -INT -g giph
    ;;
    esac
