#!/bin/bash
#TODO: Make this a bit more dynamic, but for now it doesnt matter
herbstclient -i | while read -r hook; do
    case $hook in
	rule*)
	    bash "$HOME/.config/herbstluftwm/dialogs"
	    echo "RULE"
	    ;;
    esac
done
