#!/usr/bin/lua
--Increment tags, only for the currently focused monitor
--Tags on first monitor
input = {...}
tags={}
tags1={1,3,4,5,6,a,s}
tags2={2,7}
tags3={9,0}
local length = 6
local handle = io.popen("herbstclient attr tags.focus.name")
local result = handle:read("*a")
handle:close()
local ind = tonumber(result)
print(ind)
local inc = 0
print(inc)
for k,v in pairs(tags1) do
  if v == ind then
      print("Input")
      if input[1] == "u" then
	  print(k+1)
	  if k+1 < length then
	      print("Increment")
	      inc = tags1[k+1]
	  else
	      print("Loop back")
	      inc = tags1[1]
	  end
      else
	  print("Start "..k+1 ..  " length " .. length)
	  if k > 1 then
	      print("Decrement")
	      inc = tags1[k-2]
	      print(inc)
	  else
	      print("dec")
	      inc = tags1[length-1]
	      print(inc)
	  end
      end
  end
end
print(inc)
handle = io.popen("herbstclient use_index " .. inc)
result = handle:read("*a")
