#!/bin/bash
xrandr | grep 'VGA-1 connected' && xrandr --output eDP-1 --auto --output VGA-1 --auto --right-of eDP-1
xrandr | grep 'HDMI-1 connected' && xrandr --output eDP-1 --auto --output HDMI-1 --auto --above eDP-1
