#!/bin/bash
vga="$(xrandr | grep 'VGA-1 connected' && xrandr --output eDP-1 --auto --output VGA-1 --auto --right-of eDP-1)"
hdmi="$(xrandr | grep 'HDMI-1 connected' && xrandr --output eDP-1 --auto --output HDMI-1 --auto --left-of eDP-1)"
if [[ -z $hdmi ]];then
    hc setenv place work
else
    hc setenv place home
fi

