#!/bin/bash
hdmi="$(xrandr | grep 'HDMI-1 connected' && xrandr --output eDP-1 --auto --output HDMI-1 --auto --right-of eDP-1)"
if [[ -n $hdmi ]];then
    vga="$(xrandr | grep 'VGA-1 connected' && xrandr --output eDP-1 --auto --output VGA-1 --auto --right-of HDMI-1)"
    herbstclient setenv place home
else
    herbstclient setenv place work
    vga="$(xrandr | grep 'VGA-1 connected' && xrandr --output eDP-1 --auto --output VGA-1 --auto --right-of eDP-1)"
fi
nitrogen --restore
