#!/bin/bash
# First argument is:
# - volumeUp
# - volumeDown
# - muteToggle
# - brightnessUp
# - brightnessDown
# Second is optional, used for increment or decrement for volume or brightness
case $1 in
    "volumeUp"*)
	amixer -D pulse sset Master $2%+ && paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
    ;;
    "volumeDown"*)
	amixer -D pulse sset Master $2%- && paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
    ;;
    "muteToggle"*)
	amixer -D pulse set Master 1+ toggle
    ;;
    "brightnessUp"*)
	xbacklight -inc $2
    ;;
    "brightnessDown"*)
	xbacklight -dec $2
    ;;
esac

